# Generated by Django 4.2.7 on 2023-11-20 19:49

from django.db import migrations, models
import django.db.models.deletion
import lab8_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, validators=[lab8_app.models.validate_phone])),
                ('account', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('days', models.IntegerField(validators=[lab8_app.models.validate_days])),
                ('amount', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab8_app.material')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab8_app.provider')),
            ],
        ),
    ]
